config/routes.rb
Resolutions::Application.routes.draw do
  devise_for :users
  resources :resolutions
  resources :intends
  resources :users

  root :to => "home#index"

end

app/models/intend.rb
class Intend < ActiveRecord::Base
  belongs_to :resolution
  belongs_to :user
end

app/models/resolution.rb
class Resolution < ActiveRecord::Base

  validates :resolution,  :presence => true,
                          :length => { :minimum => 10, :maximum => 250 }

  has_many :intends
  has_many :users, :through => :intends
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  has_many :intends
  has_many :resolutions, :through => :intends
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if not current_user
      @resolutions = Resolution.find(:all, :offset => (Resolution.count * rand).to_i, :limit => 3 )
      render 'index_not_logged_in'
    else
      @my_resolutions = current_user.resolutions
      @resolutions = Resolution.all
      render 'index'
    end
  end

end

app/controllers/intends_controller.rb
class IntendsController < ApplicationController

  # POST /resolutions
  # POST /resolutions.xml
  def create
    @intend = Intend.new(:user_id => current_user.id, :resolution_id => params[:resolution_id])

    respond_to do |format|
      if not current_user.resolutions.include?(Resolution.find(params[:resolution_id])) and @intend.save
        format.html { redirect_to(resolution_path(params[:resolution_id]), :notice => 'You now intend to do this.') }
        format.xml  { render :xml => @intend, :status => :created, :location => @intend }
      else
        format.html { redirect_to(resolution_path(params[:resolution_id]), :notice => 'You already intend to do this.') }
        format.xml  { render :xml => @intend.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /intends/1
  # DELETE /intends/1.xml
  # 1 = resolution_id!
  def destroy
    @intend = current_user.intends.where(:resolution_id => params[:id])
    @intend.destroy_all

    respond_to do |format|
      format.html { redirect_to(resolution_path(params[:id])) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/resolutions_controller.rb
class ResolutionsController < ApplicationController
  before_filter :authenticate_user!

  # GET /resolutions
  # GET /resolutions.xml
  def index
    @resolutions = Resolution.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @resolutions }
    end
  end

  # GET /resolutions/1
  # GET /resolutions/1.xml
  def show
    @resolution = Resolution.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @resolution }
    end
  end

  # GET /resolutions/new
  # GET /resolutions/new.xml
  def new
    @resolution = Resolution.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @resolution }
    end
  end

  # GET /resolutions/1/edit
  def edit
    @resolution = Resolution.find(params[:id])
  end

  # POST /resolutions
  # POST /resolutions.xml
  def create
    @resolution = Resolution.new(params[:resolution])

    respond_to do |format|
      if @resolution.save
        # after create callback would be MUCH nicer, but that doesn't work
        # because current_user isn't available in your model.
        Intend.create(:user_id => current_user.id, :resolution_id => @resolution.id)

        format.html { redirect_to(@resolution, :notice => 'Resolution was successfully created.') }
        format.xml  { render :xml => @resolution, :status => :created, :location => @resolution }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @resolution.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /resolutions/1
  # PUT /resolutions/1.xml
  def update
    @resolution = Resolution.find(params[:id])

    respond_to do |format|
      if @resolution.update_attributes(params[:resolution])
        format.html { redirect_to(@resolution, :notice => 'Resolution was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @resolution.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /resolutions/1
  # DELETE /resolutions/1.xml
  def destroy
    @resolution = Resolution.find(params[:id])
    @resolution.destroy

    respond_to do |format|
      format.html { redirect_to(resolutions_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.find(:all)
  end


  def show

	@user = User.find(params[:id])

  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/intends_helper.rb
module IntendsHelper
end

app/helpers/resolutions_helper.rb
module ResolutionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/index.html.erb
<div class="grid_9">
	<h1>My resolutions</h1>
	<% if @my_resolutions.size > 0 %>
		<ul>
			<% @my_resolutions.each do |resolution| %>
				<li><%= link_to resolution.resolution, resolution %></li>
			<% end %>
		</ul>
	<% else %>
		<p>You don't have any resolutions just yet. Start browsing around all resolutions, and pick some you like.</p>
	<% end %>

	<h1>All resolutions</h1>
	<ul>
		<% @resolutions.each do |resolution| %>
			<li>
				<%= link_to resolution.resolution, resolution %>
				<% if resolution.users.include?(current_user) %> <strong>- Already on your list</strong><% end %>
			</li>
		<% end %>
	</ul>

	<p>Found nothing interesting? <%= link_to 'Create a new resolution', new_resolution_path %></p>
</div>

app/views/home/index_not_logged_in.html.erb
<h1>What are your resolutions?</h1>

<div class="grid_7">
<h3>With <strong>yourresolutions</strong> you can easily create your commitments for the upcoming year! You can share your resolutions with friends and see what their personal goals, projects or habit changes are.</h3>
<h3>Go <%= link_to 'ahead', new_resolution_path %> and let your resolutions come true in 2011!</h3>

<div class="grid_10">
<ul class="randomhome">
<% @resolutions.each do |resolution| %>
<li><%= link_to resolution.resolution, resolution %></li>
<% end %>
</ul>
</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Resolutions</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<div class="container_12">
  
  <div class="grid_6">
  <a href="/"><%= image_tag("logo.png", :alt => "Logo", :class => "logo") %></a>
  
  </div>
  
  <div class="grid_4">
    <div class="headright">
    <% if user_signed_in? %>
						Hello, <%= current_user.email %><br />
						<%= link_to('Profile', edit_registration_path(current_user)) %> / <%= link_to('Logout', destroy_user_session_path) %>
					<% else %>
					   <ul class="login">
               <li><%= link_to('Login', new_user_session_path) %> </li>
               <li><%= link_to('Register', new_user_registration_path) %></li>
             </ul>
					<% end %>

    </div>
  
  </div>
  
  <% if flash[:notice] %>
    <div class="grid_6">
      <p id="notice" ><%= notice %></p>
    </div>
  <% end %>
  
  <div class="grid_10 content">
  
  <%= yield %>

  </div>
  
</div>

</body>
</html>

app/views/resolutions/_form.html.erb
<%= form_for(@resolution) do |f| %>
  <% if @resolution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resolution.errors.count, "error") %> prohibited this resolution from being saved:</h2>

      <ul>
      <% @resolution.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :resolution %><br />
    <%= f.text_field :resolution %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resolutions/edit.html.erb
<h1>Editing resolution</h1>

<%= render 'form' %>

<%= link_to 'Show', @resolution %> |
<%= link_to 'Back', resolutions_path %>

app/views/resolutions/index.html.erb
<h1>Listing resolutions</h1>

<table>
  <tr>
    <th align="left">Resolution</th>
    <th align="left" style="padding-left:10px;">Created</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @resolutions.each do |resolution| %>
  <tr>
    <td width="400px"><%= resolution.resolution %></td>
    <td style="padding-left:10px;color:#a1a1a1;"><%= resolution.created_at %></td>
    <td style="padding-left:10px;"><%= link_to 'Show', resolution %></td>
    <td style="padding-left:10px;"><%= link_to 'Edit', edit_resolution_path(resolution) %></td>
    <td style="padding-left:10px;"><%= link_to 'Destroy', resolution, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Resolution', new_resolution_path %>

app/views/resolutions/new.html.erb
<h1>New resolution</h1>

<%= render 'form' %>

<%= link_to 'Back', resolutions_path %>

app/views/resolutions/show.html.erb
<h2><%= @resolution.resolution %></h2>

<% if @resolution.users.size > 0 %>
	<h3>People intending to do this</h3>
	<ul>
		<% @resolution.users.each do |user| %>
			<li><%= link_to user.email, user_path(user) %></li>
		<% end %>
	</ul>

	<% if not current_user.resolutions.exists?(@resolution) %>
		<%= button_to "Me too!", intends_path(:resolution_id => @resolution.id) %>
	<% else %>
		<%= link_to "Nah, changed my mind", intend_path(:id => @resolution.id), :confirm => "Are you sure?", :method => :delete %>
	<% end %>
<% else %>
  <div class="grid_9">
	<h3>Even the person who invented this resolution doesn't have the intention to do it anymore. Do you?</h3><br/>
	 
	<%= button_to "Sure thing bro!", intends_path(:resolution_id => @resolution.id) %>
<% end %>
</div>

app/views/users/index.html.erb
<h1>All users</h1>

<div class="grid_7">
<h3>Here you can see all the <strong>users</strong> that have shared there resolutions</h3>
<ul>
<% @users.resolutions.each do |user| %>
<li><a href="<%= user_path(user) %>"><%= user.real_name %></a></li>
<% end %>
</ul>
</div>

app/views/users/show.html.erb
<h1><%= @user.real_name %>'s resolutions</h1>
<ul>
<% @user.resolutions.each do |resolution| %>
<li><a href="<%= resolution_path(resolution) %>"><%= resolution.resolution %></a></li>
<% end %>
</ul>